.DEFAULT_GOAL := help

PROJECT_ROOT := $(shell git rev-parse --show-toplevel)
TERRAFORM_DOCS_IMAGE := quay.io/terraform-docs/terraform-docs:0.20.0
DOCS_MARKER := ### Module Documentation

# --- parse-time guards -------------------------------------------------------
# These run BEFORE any target. A missing tool or an uninstalled git hook fails
# here, locally, with a pointer — instead of silently passing to CI.
EXECUTABLES := mise pre-commit docker
_ := $(foreach e,$(EXECUTABLES),\
       $(if $(shell command -v $(e) 2>/dev/null),,\
         $(error "$(e)" not found in PATH — see README Setup)))

ifeq (,$(wildcard $(PROJECT_ROOT)/.git/hooks/pre-commit))
  $(error git hook not installed — run: pre-commit install)
endif
ifeq (,$(wildcard $(PROJECT_ROOT)/.git/hooks/commit-msg))
  $(error commit-msg hook not installed — run: pre-commit install --hook-type commit-msg)
endif

.guard-%:
	@[ "$($*)" ] || { echo "ERROR: $* is not set. e.g. make $(MAKECMDGOALS) $*=<value>"; exit 1; }

# -----------------------------------------------------------------------------
help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
	  | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2}'

fmt: ## Format all Terraform
	@mise exec -- tofu fmt -recursive $(PROJECT_ROOT)

validate: ## terraform validate every module and example (no credentials needed)
	@set -e; for d in $$(find $(PROJECT_ROOT) -name '*.tf' -not -path '*/.*' -exec dirname {} \; | sort -u); do \
	  echo "--> $$d"; \
	  ( cd $$d && mise exec -- tofu init -backend=false -input=false -no-color >/dev/null && \
	    mise exec -- tofu validate -no-color ); \
	done

docs: .guard-MODULE ## Regenerate one module's README docs. make docs MODULE=networking/vpc
	@test -f $(MODULE)/README.md || { echo "no README at $(MODULE) — use 'make new-module'"; exit 1; }
	@sed -i '' '/$(DOCS_MARKER)/,$$d' $(MODULE)/README.md
	@printf '$(DOCS_MARKER)\n\n_Autogenerated. Do not edit below this line._\n\n' >> $(MODULE)/README.md
	@docker run --rm -v $(PROJECT_ROOT):/data $(TERRAFORM_DOCS_IMAGE) \
	    markdown table /data/$(MODULE)/ >> $(MODULE)/README.md
	@echo "docs updated: $(MODULE)/README.md"

new-module: .guard-CATEGORY .guard-NAME ## Scaffold a module. make new-module CATEGORY=networking NAME=vpc
	@$(PROJECT_ROOT)/scripts/new_module.py $(CATEGORY) $(NAME)

check-pins: ## Fail if any git:: source is missing ?ref=
	@! grep -rn 'git::' --include='*.tf' $(PROJECT_ROOT) | grep -v '?ref=' \
	  || { echo "unpinned git:: source above — add ?ref=<tag>"; exit 1; }

check-self-ref: ## Fail if a module git:: references THIS repo (use relative paths)
	@! grep -rn 'git::.*infra-modules' --include='*.tf' $(PROJECT_ROOT) \
	  || { echo "self-referencing source above — use a relative path instead"; exit 1; }

.PHONY: help fmt validate docs new-module check-pins check-self-ref
