#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Scaffold a new module.

Creates every file the conventions require, so nothing has to be remembered:
main.tf, variables.tf, outputs.tf, versions.tf, README.md (with the docs
marker already present) and examples/simple/.

Charizard ended up with 12 modules and no README because their tooling only
ever APPENDED to an existing file. Creating the file up front is the fix.
"""
import sys
from pathlib import Path

FILES = {
    "main.tf": '# {name}\n#\n# Internal composition uses RELATIVE paths, never git:: to this repo.\n# A module pinned to an old version of its own sibling is undetectable.\n',
    "variables.tf": '# Inputs. Never hardcode account ids, regions or environment names.\n',
    "outputs.tf": '# Outputs. Consumers depend on these — treat them as a public contract.\n',
    "versions.tf": '''terraform {{
  required_version = ">= 1.6.0, < 2.0.0"

  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = ">= 5.0, < 7.0"
    }}
  }}
}}
''',
    "README.md": '''# {name}

<!-- What this module does, and when to use it. Human-owned. -->

## Usage

```hcl
terraform {{
  source = "git::git@github.com:adi4fab/infra-modules.git//{category}/{name}?ref=v0.1.0"
}}
```

### Module Documentation

_Autogenerated. Do not edit below this line._
''',
    "examples/simple/main.tf": '''# Doubles as the module's test — `tofu validate` runs it in CI.
# Documentation that cannot go stale.
module "{name}" {{
  source = "../.."
}}
''',
}


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: new_module.py <category> <name>", file=sys.stderr)
        return 2
    category, name = sys.argv[1], sys.argv[2]

    root = Path(__file__).resolve().parent.parent
    catalog = sorted(p.name for p in root.iterdir() if p.is_dir() and not p.name.startswith((".", "_")) and p.name != "scripts")

    target = root / category / name
    if target.exists():
        print(f"ERROR: {category}/{name} already exists", file=sys.stderr)
        return 1

    for rel, tmpl in FILES.items():
        f = target / rel
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(tmpl.format(name=name, category=category))
        print(f"  created {f.relative_to(root)}")

    print(f"\nnext: write the module, then `make docs MODULE={category}/{name}`")
    if category not in catalog and catalog:
        print(f"note: new category '{category}'. Existing: {', '.join(catalog)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
